"use client";
import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { contactSchema } from "@/lib/contact/schema";

type FormState = "idle" | "submitting" | "success" | "error";
type Fields = { name: string; phone: string; email: string; message: string; website: string };
const initial: Fields = { name: "", phone: "", email: "", message: "", website: "" };

export function ContactForm({ successMode = "inline" }: { successMode?: "inline" | "redirect" }) {
  const [fields, setFields] = useState<Fields>(initial); const [errors, setErrors] = useState<Record<string, string>>({}); const [state, setState] = useState<FormState>("idle");
  function update(key: keyof Fields, value: string) { setFields((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: "" })); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const parsed = contactSchema.safeParse(fields); if (!parsed.success) { const next: Record<string, string> = {}; for (const issue of parsed.error.issues) next[String(issue.path[0])] = issue.message; setErrors(next); setState("error"); return; } setState("submitting"); try { const response = await fetch("/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(fields) }); if (!response.ok) throw new Error(); if (successMode === "redirect") window.location.assign("/thank-you"); else { setState("success"); setFields(initial); } } catch { setState("error"); } }
  if (state === "success") return <div role="status" className="rounded-token border border-line bg-surface p-6"><h3 className="font-semibold">Thanks — we received your message.</h3><p className="mt-2 text-sm text-muted">We’ll be in touch soon.</p></div>;
  return <form onSubmit={submit} noValidate className="space-y-5" aria-describedby={state === "error" ? "form-error" : undefined}><div className="grid gap-5 sm:grid-cols-2"><Field label="Name" name="name" value={fields.name} error={errors.name} onChange={(value) => update("name", value)} /><Field label="Phone" name="phone" type="tel" value={fields.phone} error={errors.phone} onChange={(value) => update("phone", value)} /><Field label="Email" name="email" type="email" value={fields.email} error={errors.email} onChange={(value) => update("email", value)} /></div><div className="sr-only" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" tabIndex={-1} autoComplete="off" value={fields.website} onChange={(event) => update("website", event.target.value)} /></div><div><label htmlFor="message" className="mb-2 block text-sm font-medium">Message</label><textarea id="message" name="message" rows={5} value={fields.message} onChange={(event) => update("message", event.target.value)} aria-invalid={Boolean(errors.message)} aria-describedby={errors.message ? "message-error" : undefined} className="w-full rounded-md border border-line bg-white px-3 py-3 outline-none focus:border-accent focus:ring-2 focus:ring-accent/20" />{errors.message && <p id="message-error" className="mt-1 text-sm text-red-700">{errors.message}</p>}</div>{state === "error" && !Object.values(errors).some(Boolean) && <p id="form-error" role="alert" className="text-sm text-red-700">Something went wrong. Please try again.</p>}<Button type="submit" disabled={state === "submitting"}>{state === "submitting" ? "Sending…" : "Send message"}</Button></form>;
}
function Field({ label, name, type = "text", value, error, onChange }: { label: string; name: keyof Fields; type?: string; value: string; error?: string; onChange: (value: string) => void }) { const id = `contact-${name}`; return <div><label htmlFor={id} className="mb-2 block text-sm font-medium">{label}</label><input id={id} name={name} type={type} value={value} onChange={(event) => onChange(event.target.value)} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} className="w-full rounded-md border border-line bg-white px-3 py-3 outline-none focus:border-accent focus:ring-2 focus:ring-accent/20" />{error && <p id={`${id}-error`} className="mt-1 text-sm text-red-700">{error}</p>}</div>; }
