"use client";
import { FormEvent, useState } from "react";
import { Button } from "@/components/ui/button";
import { contactSchema } from "@/lib/contact/schema";

type FormState = "idle" | "submitting" | "success" | "error";
type Fields = { name: string; phone: string; email: string; message: string; website: string };
const initial: Fields = { name: "", phone: "", email: "", message: "", website: "" };

export function ContactForm({ successMode = "inline" }: { successMode?: "inline" | "redirect" }) {
  const [fields, setFields] = useState<Fields>(initial); const [errors, setErrors] = useState<Record<string, string>>({}); const [state, setState] = useState<FormState>("idle");
  function update(key: keyof Fields, value: string) { setFields((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: "" })); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const parsed = contactSchema.safeParse(fields); if (!parsed.success) { const next: Record<string, string> = {}; for (const issue of parsed.error.issues) next[String(issue.path[0])] = issue.message; setErrors(next); setState("error"); return; } setState("submitting"); try { const response = await fetch("/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(fields) }); if (!response.ok) throw new Error(); if (successMode === "redirect") window.location.assign("/thank-you"); else { setState("success"); setFields(initial); } } catch { setState("error"); } }
  if (state === "success") return <div role="status" className="rounded-token border border-line bg-surface p-6"><h3 className="font-semibold">Дякуємо — заявку отримано.</h3><p className="mt-2 text-sm text-muted">Ми зв&apos;яжемося з вами найближчим часом.</p></div>;
  return <form onSubmit={submit} noValidate className="contact-form" aria-describedby={state === "error" ? "form-error" : undefined}><div className="contact-form__fields"><Field label="Ім'я" placeholder="Ваше ім&apos;я" name="name" value={fields.name} error={errors.name} onChange={(value) => update("name", value)} /><Field label="Телефон" placeholder="+380" name="phone" type="tel" value={fields.phone} error={errors.phone} onChange={(value) => update("phone", value)} /><Field label="Email" placeholder="Ваш email" name="email" type="email" value={fields.email} error={errors.email} onChange={(value) => update("email", value)} /></div><div className="sr-only" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" tabIndex={-1} autoComplete="off" value={fields.website} onChange={(event) => update("website", event.target.value)} /></div><div className="contact-form__message"><label htmlFor="message">Повідомлення <span>(опціонально)</span></label><textarea id="message" name="message" placeholder="Деталі вашого замовлення..." rows={4} value={fields.message} onChange={(event) => update("message", event.target.value)} aria-invalid={Boolean(errors.message)} aria-describedby={errors.message ? "message-error" : undefined} />{errors.message && <p id="message-error" className="mt-1 text-sm text-red-700">{errors.message}</p>}</div>{state === "error" && !Object.values(errors).some(Boolean) && <p id="form-error" role="alert" className="text-sm text-red-700">Не вдалося надіслати заявку. Спробуйте ще раз.</p>}<Button className="contact-form__submit" type="submit" disabled={state === "submitting"}>{state === "submitting" ? "Надсилання…" : "ВІДПРАВИТИ  →"}</Button></form>;
}
function Field({ label, placeholder, name, type = "text", value, error, onChange }: { label: string; placeholder: string; name: keyof Fields; type?: string; value: string; error?: string; onChange: (value: string) => void }) { const id = `contact-${name}`; return <div className={`contact-field contact-field--${name}`}><label htmlFor={id}>{label}</label><input id={id} name={name} type={type} placeholder={placeholder} value={value} onChange={(event) => onChange(event.target.value)} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} />{error && <p id={`${id}-error`} className="mt-1 text-sm text-red-700">{error}</p>}</div>; }
